// Code generated by mockery v2.40.1. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// mockStringerFunc is an autogenerated mock type for the stringerFunc type
type mockStringerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *mockStringerFunc) Execute() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// newMockStringerFunc creates a new instance of mockStringerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStringerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStringerFunc {
	mock := &mockStringerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
